# Peng Seyha - Spring Boot Midterm

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5434/demo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true